/*****************************CONFIGURE DATABASE LEVEL AUDIT SPECIFICATION EVENT GROUPS*********************************/
USE [master]

DECLARE @DBNAME VARCHAR(255)
DECLARE @command VARCHAR(2000)

DECLARE DBS_1 CURSOR FOR
SELECT NAME FROM sys.databases WHERE NAME NOT IN ('master','tempdb','model','msdb','rdsadmin')
OPEN DBS_1
FETCH NEXT FROM DBS_1 INTO @DBNAME
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @command= 'USE [' + @DBNAME +'];' +
	'IF EXISTS (SELECT * FROM sys.database_audit_specifications WHERE name = N''' + @DBNAME +'_DB_MGMT_SPEC'')' +
	'BEGIN ' +
	'ALTER DATABASE AUDIT SPECIFICATION ['+@DBNAME+ '_DB_MGMT_SPEC] WITH (STATE = OFF);' +
	'DROP DATABASE AUDIT SPECIFICATION ['+@DBNAME+ '_DB_MGMT_SPEC];'+
	'END '+
	'CREATE DATABASE AUDIT SPECIFICATION ['+@DBNAME+ '_DB_MGMT_SPEC]'+
	'FOR SERVER AUDIT [SQL_NATIVE_AUDIT]' +
	'ADD (AUDIT_CHANGE_GROUP),'+
	'ADD (DATABASE_OBJECT_CHANGE_GROUP),'+
	'ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),'+
	'ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),'+
	'ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),'+
	'ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),'+
	'ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),'+
	'ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP),'+
	'ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),'+
	'ADD (DATABASE_PERMISSION_CHANGE_GROUP),'+
	'ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP)'+
	'WITH (STATE = ON);'
	EXECUTE (@command);
FETCH NEXT FROM DBS_1 INTO @DBNAME
END
CLOSE DBS_1
DEALLOCATE DBS_1
