/***********************************CREATE SERVER AUDIT PER AWS REQUIREMENTS********************************************/
USE [master]

IF  EXISTS (SELECT * FROM sys.server_audits WHERE name = N'SQL_NATIVE_AUDIT')
BEGIN
ALTER SERVER AUDIT [SQL_NATIVE_AUDIT] WITH (STATE = OFF)
DROP SERVER AUDIT [SQL_NATIVE_AUDIT]
END

CREATE SERVER AUDIT [SQL_NATIVE_AUDIT]
TO FILE
(	FILEPATH = N'D:\rdsdbdata\SQLAudit'
	,MAXSIZE = 30 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
WHERE
(
	[database_name]<>'rdsadmin'
)

ALTER SERVER AUDIT [SQL_NATIVE_AUDIT]
WITH (STATE = ON)